import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillCode,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>About me</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">SoloDev#7416</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              SoloDev
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Developer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              I am a developer who makes scripts, so you can get an unfair advantage in an lego game. In my spare time I also programm discord bots.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <AiFillCode />
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">My Story</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since 2020 I tried to be an developer for roblox exploit scripts, but I didnt find any tutorials so I just quit for now.
              After some time I got into exploiting again and I made my first script! Yeah it was some skidded shit, but I learned alot from it.
              This is, when I realised its pretty fun to make scripts, to get an unfair advantage. So I looked up some youtube tutorials on how to exploit.
              The best guy that made these tutorials is called wYn. When I finished watching all his videos I got synapse x which is one of the many great paid executors out there.
              After I got synapse x I read through the documentation and I learned so much from it. I am still learning new stuff every day!
              <span className="text-teal-500"></span>
               <span className="text-teal-500"> </span>
              
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              wYn: youtube.com/channel/UCnPtFq0xgbCLLuW0Mc383fA,
              synapse x: x.synapse.to,
              synapse docs: x.synapse.to/docs
            </p>
          </div>
        </section>
              </main>
    </div>
  );
}
